### PR TITLE
feat: handle non agent fields on MDC for Log4j2

### PR DESCRIPTION
**Pull request by thomasdac**
Hi guys!

We use MDC on Log4j2 to carry additional information that is pertinent to troubleshooting (E.g.: User ID, Order Number, Product Identifier, etc). These fields are very helpful in searching the logs in the Web Console.

The current version of NewRelic only records fields coming from the agent. The idea of this implementation is to include the other MDC fields in the log, without conflicting with the existing ones.

Thanks!

### CODE REVIEW

**Comment by kford-newrelic** [comment]
@thomasdac thank you for this PR!

We're currently targeting the addition of MDC support to the logging in the `newrelic-java-agent` itself (our [automatic LiC](https://docs.newrelic.com/docs/logs/logs-context/java-configure-logs-context-all/#automatic) feature), so it will take some time before we can circle back to doing the same for `java-log-extensions` but it's a worthy idea to consider.

Thanks again!

**Comment by jbisotti** [comment]
+1

**Comment by kford-newrelic** [comment]
Have not been able to action this during the Jan-Mar quarter. Will try to target for the next Apr-Jun quarter.

**Comment by jasonjkeller** [comment]
Closing this PR. Configurable MDC support will be added for all supported logging libraries in the linked PR and will be in the java-log-extensions 3.0.0 release: https://github.com/newrelic/java-log-extensions/pull/75

**Pull request closed without merging**
