### PR TITLE
Logback 1.1 support, fix for double-quotes in messages in Logback 1.2 support

### PR DESCRIPTION
**Pull request by sschwartzman**
Logback1.1.x module (including test harness and test app) called "logback11". Differences are all in NewRelicEncoder.java - `doEncode()` is a void function that writes to outputStream, whereas in logback 1.2, `encode()` returns a byte[] that is written to the stream by code in logback.

The double-quotes "bug" came up in Qi Yang's testing of the logback11 module, where logs being written to it had double-quotes in the "message" field that were escaped upon passage to Jackson, but may have lost those escape characters in subsequent transforms, which is causing an invalid payload. An easy workaround is to replace double-quotes with single-quotes in those messages.

Example of invalid payload encountered:
```
{
  "message": "Completed refreshing config for bucket "(redacted)"",
  "timestamp": 1576084800136,
  "log.level": "DEBUG",
  "logger.name": "com.couchbase.client.core.config.refresher.CarrierRefresher",
  "thread.name": "cb-computations-16",
  "class.name": "com.couchbase.client.core.utils.Buffers$2$1",
  "method.name": "onCompleted",
  "line.number": 70,
  "sourceId": "SourceId=localhost.localdomain|(redacted)",
  "hostname": "(redacted)",
  "entity.type": "SERVICE",
  "entity.guid": "(redacted)",
  "entity.name": "(redacted)"
}
```

Fixed payload:
```json
{
  "message": "Completed refreshing config for bucket '(redacted)'",
  "timestamp": 1576084800136,
  "log.level": "DEBUG",
  "logger.name": "com.couchbase.client.core.config.refresher.CarrierRefresher",
  "thread.name": "cb-computations-16",
  "class.name": "com.couchbase.client.core.utils.Buffers$2$1",
  "method.name": "onCompleted",
  "line.number": 70,
  "sourceId": "SourceId=localhost.localdomain|(redacted)",
  "hostname": "(redacted)",
  "entity.type": "SERVICE",
  "entity.guid": "(redacted)",
  "entity.name": "(redacted)"
}
```

### CODE REVIEW

**Comment by jeffalder** [comment]
First: THANK YOU for the contribution.

Second: I put some double-quotes in a message and it logged correctly. 

example change:
```diff
-        logger.error("this contains a throwable", t);
+        logger.error("this contains a \"throwable\"", t);
```
result:
```
{"message":"this contains a \"throwable\"","timestamp":...
```

I'm not clear where the problem occurred with the payload, but it's not in the logging library. I'm not super comfortable changing the contents of the user's log message like this. Can Qi Yang dig more into where this was happening? Is there an issue in the log forwarder in use? 

I pushed up commit 5e763bd to add quotes to the example app as well as remove the escaping from logback 1.2.

There was a problem in the spotbugs filter for logback11; I discovered this running `./gradlew check`. I've pushed up commit 4388f85 to fix the filter and `check` passes now.

**Comment by jeffalder** [comment]
Ignore the publish pipeline; I don't know why it's running and it's not supposed to.

**Comment by jeffalder** [comment]
@sschwartzman - If we back out the double-quote changes, I'm happy to merge this and publish it.

If we need the double-quote changes, I need to know more about why, since the extensions produce valid JSON as-is without the change.

Also, for grins, can you sign off on the CLA? If it's not working, reach out to @tangollama .

**Comment by sschwartzman** [comment]
@jeffalder i'm fine with that, and just signed the CLA. Do you need me to back out the double quote changes?

**Pull request merged**
